"""Validates and constrains SQL generated by the text-to-SQL agent before
it ever reaches the database. This is a second, independent layer of
defense on top of the agent_readonly DB role (see the Alembic migration
that created it) -- the role makes writes physically impossible; this
module makes sure a wildly wrong or adversarial query never even gets
sent, and that a runaway SELECT can't return an unbounded result set.

Structural validation (walking the parsed AST for forbidden node types)
is used instead of a keyword blacklist -- text that isn't actually a
SELECT won't parse into a Select node at all, so there's no string
pattern to bypass.
"""

from __future__ import annotations

import sqlglot
from sqlglot import exp


class UnsafeQueryError(ValueError):
    """Raised when a generated query fails validation -- never executed."""


def validate_and_limit(sql: str, row_limit: int) -> str:
    """Confirms `sql` is exactly one SELECT (a WITH ... SELECT is fine --
    confirmed via sqlglot that a CTE's top-level node type is still
    Select), then caps its LIMIT to `row_limit` -- injecting one if
    absent, lowering it if the query's own LIMIT exceeds the cap. Returns
    the (possibly rewritten) SQL to execute. Raises UnsafeQueryError for
    anything else, with no partial/best-effort execution."""
    try:
        statements = sqlglot.parse(sql, dialect="postgres")
    except Exception as exc:
        raise UnsafeQueryError(f"Could not parse SQL: {exc}") from exc

    if len(statements) != 1:
        raise UnsafeQueryError(f"Expected exactly one statement, got {len(statements)}")

    statement = statements[0]
    if statement is None or not isinstance(statement, exp.Select):
        kind = type(statement).__name__ if statement is not None else "empty statement"
        raise UnsafeQueryError(f"Only SELECT statements are allowed, got {kind}")

    existing_limit = statement.find(exp.Limit)
    if existing_limit is None:
        statement = statement.limit(row_limit)
    else:
        try:
            current_value = int(existing_limit.expression.sql())
        except (ValueError, AttributeError):
            current_value = None
        if current_value is None or current_value > row_limit:
            statement = statement.limit(row_limit)

    return statement.sql(dialect="postgres")
