"""initial schema

Revision ID: 43d075184e32
Revises: 
Create Date: 2026-07-20 14:42:12.288300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d075184e32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nba_player_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('height_in', sa.SmallInteger(), nullable=True),
    sa.Column('weight_lb', sa.SmallInteger(), nullable=True),
    sa.Column('draft_year', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players'))
    )
    op.create_index(op.f('ix_players_nba_player_id'), 'players', ['nba_player_id'], unique=True)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_label', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seasons'))
    )
    op.create_index(op.f('ix_seasons_season_label'), 'seasons', ['season_label'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nba_team_id', sa.Integer(), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('conference', sa.String(length=10), nullable=True),
    sa.Column('division', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    op.create_index(op.f('ix_teams_nba_team_id'), 'teams', ['nba_team_id'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nba_game_id', sa.String(length=20), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('game_type', sa.String(length=20), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.SmallInteger(), nullable=True),
    sa.Column('away_score', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('home_team_id <> away_team_id', name=op.f('ck_games_distinct_teams')),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], name=op.f('fk_games_away_team_id_teams')),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], name=op.f('fk_games_home_team_id_teams')),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_games_season_id_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games'))
    )
    op.create_index(op.f('ix_games_away_team_id'), 'games', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_games_game_date'), 'games', ['game_date'], unique=False)
    op.create_index(op.f('ix_games_game_type'), 'games', ['game_type'], unique=False)
    op.create_index(op.f('ix_games_home_team_id'), 'games', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_games_nba_game_id'), 'games', ['nba_game_id'], unique=True)
    op.create_index(op.f('ix_games_season_id'), 'games', ['season_id'], unique=False)
    op.create_table('player_game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('points', sa.SmallInteger(), nullable=True),
    sa.Column('rebounds', sa.SmallInteger(), nullable=True),
    sa.Column('assists', sa.SmallInteger(), nullable=True),
    sa.Column('steals', sa.SmallInteger(), nullable=True),
    sa.Column('blocks', sa.SmallInteger(), nullable=True),
    sa.Column('turnovers', sa.SmallInteger(), nullable=True),
    sa.Column('fg_made', sa.SmallInteger(), nullable=True),
    sa.Column('fg_attempted', sa.SmallInteger(), nullable=True),
    sa.Column('fg3_made', sa.SmallInteger(), nullable=True),
    sa.Column('fg3_attempted', sa.SmallInteger(), nullable=True),
    sa.Column('ft_made', sa.SmallInteger(), nullable=True),
    sa.Column('ft_attempted', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('minutes >= 0', name=op.f('ck_player_game_stats_minutes_nonneg')),
    sa.CheckConstraint('points >= 0', name=op.f('ck_player_game_stats_points_nonneg')),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_player_game_stats_game_id_games')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_game_stats_player_id_players')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_player_game_stats_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_game_stats')),
    sa.UniqueConstraint('game_id', 'player_id', name='uq_player_game_stats_game_id_player_id')
    )
    op.create_index('ix_player_game_stats_player_id_game_id', 'player_game_stats', ['player_id', 'game_id'], unique=False)
    op.create_index(op.f('ix_player_game_stats_team_id'), 'player_game_stats', ['team_id'], unique=False)
    op.create_table('team_game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.SmallInteger(), nullable=True),
    sa.Column('rebounds', sa.SmallInteger(), nullable=True),
    sa.Column('assists', sa.SmallInteger(), nullable=True),
    sa.Column('turnovers', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_team_game_stats_game_id_games')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_game_stats_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_game_stats')),
    sa.UniqueConstraint('game_id', 'team_id', name='uq_team_game_stats_game_id_team_id')
    )
    op.create_index(op.f('ix_team_game_stats_game_id'), 'team_game_stats', ['game_id'], unique=False)
    op.create_index(op.f('ix_team_game_stats_team_id'), 'team_game_stats', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_game_stats_team_id'), table_name='team_game_stats')
    op.drop_index(op.f('ix_team_game_stats_game_id'), table_name='team_game_stats')
    op.drop_table('team_game_stats')
    op.drop_index(op.f('ix_player_game_stats_team_id'), table_name='player_game_stats')
    op.drop_index('ix_player_game_stats_player_id_game_id', table_name='player_game_stats')
    op.drop_table('player_game_stats')
    op.drop_index(op.f('ix_games_season_id'), table_name='games')
    op.drop_index(op.f('ix_games_nba_game_id'), table_name='games')
    op.drop_index(op.f('ix_games_home_team_id'), table_name='games')
    op.drop_index(op.f('ix_games_game_type'), table_name='games')
    op.drop_index(op.f('ix_games_game_date'), table_name='games')
    op.drop_index(op.f('ix_games_away_team_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_teams_nba_team_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_seasons_season_label'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_players_nba_player_id'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
