"""add play_by_play table

Revision ID: c84aa018ff7e
Revises: 43d075184e32
Create Date: 2026-07-21 12:10:33.292481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c84aa018ff7e'
down_revision: Union[str, Sequence[str], None] = '43d075184e32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('play_by_play',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('period', sa.SmallInteger(), nullable=False),
    sa.Column('clock', sa.String(length=20), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('sub_type', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('player2_id', sa.Integer(), nullable=True),
    sa.Column('player3_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('score_home', sa.SmallInteger(), nullable=True),
    sa.Column('score_away', sa.SmallInteger(), nullable=True),
    sa.Column('shot_x', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('shot_y', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('shot_distance', sa.SmallInteger(), nullable=True),
    sa.Column('shot_made', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_play_by_play_game_id_games')),
    sa.ForeignKeyConstraint(['player2_id'], ['players.id'], name=op.f('fk_play_by_play_player2_id_players')),
    sa.ForeignKeyConstraint(['player3_id'], ['players.id'], name=op.f('fk_play_by_play_player3_id_players')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_play_by_play_player_id_players')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_play_by_play_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_play_by_play')),
    sa.UniqueConstraint('game_id', 'sequence', name='uq_play_by_play_game_id_sequence')
    )
    op.create_index(op.f('ix_play_by_play_event_type'), 'play_by_play', ['event_type'], unique=False)
    op.create_index(op.f('ix_play_by_play_game_id'), 'play_by_play', ['game_id'], unique=False)
    op.create_index(op.f('ix_play_by_play_player_id'), 'play_by_play', ['player_id'], unique=False)
    op.create_index(op.f('ix_play_by_play_team_id'), 'play_by_play', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_play_by_play_team_id'), table_name='play_by_play')
    op.drop_index(op.f('ix_play_by_play_player_id'), table_name='play_by_play')
    op.drop_index(op.f('ix_play_by_play_game_id'), table_name='play_by_play')
    op.drop_index(op.f('ix_play_by_play_event_type'), table_name='play_by_play')
    op.drop_table('play_by_play')
    # ### end Alembic commands ###
